rails-server/config/routes.rb
Rails.application.routes.draw do
  # resources :woofs
  resources :woofs, except: [:new, :edit]

  # get 'woofs' => 'woofs#index'
  # get 'woofs/:id' => 'woofs#show'
  # post 'woofs' => 'woofs#create'
  # patch 'woofs/:id' => 'woofs#update'
  # delete 'woofs/:id' => 'woofs#destroy'
end

rails-server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-server/app/models/woof.rb
class Woof < ApplicationRecord

end

rails-server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-server/app/controllers/woofs_controller.rb
class WoofsController < ApplicationController
  before_action :set_woof, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token

  # GET /woofs
  # GET /woofs.json
  def index
    @woofs = Woof.all

    render json: @woofs
  end

  # GET /woofs/1
  # GET /woofs/1.json
  def show
    render json: @woof
  end

  # POST /woofs
  # POST /woofs.json
  def create
    @woof = Woof.new(woof_params)
    if @woof.save
      render json: @woof, status: :created, location: @woof
    else
      render json: @woof.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /woofs/1
  # PATCH/PUT /woofs/1.json
  def update
    if @woof.update(woof_params)
      head :no_content
    else
      render json: @woof.errors, status: :unprocessable_entity
    end
  end

  # DELETE /woofs/1
  # DELETE /woofs/1.json
  def destroy
    @woof.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_woof
      @woof = Woof.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def woof_params
      params.require(:woof).permit(:name, :content)
    end
end

rails-server/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-server/app/helpers/woofs_helper.rb
module WoofsHelper
end

rails-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-server/app/views/woofs/_form.html.erb
<%= form_with(model: woof, local: true) do |form| %>
  <% if woof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(woof.errors.count, "error") %> prohibited this woof from being saved:</h2>

      <ul>
        <% woof.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-server/app/views/woofs/edit.html.erb
<h1>Editing Woof</h1>

<%= render 'form', woof: @woof %>

<%= link_to 'Show', @woof %> |
<%= link_to 'Back', woofs_path %>

rails-server/app/views/woofs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Woofs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @woofs.each do |woof| %>
      <tr>
        <td><%= woof.name %></td>
        <td><%= woof.content %></td>
        <td><%= link_to 'Show', woof %></td>
        <td><%= link_to 'Edit', edit_woof_path(woof) %></td>
        <td><%= link_to 'Destroy', woof, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Woof', new_woof_path %>

rails-server/app/views/woofs/new.html.erb
<h1>New Woof</h1>

<%= render 'form', woof: @woof %>

<%= link_to 'Back', woofs_path %>

rails-server/app/views/woofs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @woof.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @woof.content %>
</p>

<%= link_to 'Edit', edit_woof_path(@woof) %> |
<%= link_to 'Back', woofs_path %>